version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: neoshala-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: neoshala
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./Backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - neoshala-network

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: neoshala-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb://admin:password123@mongodb:27017/neoshala?authSource=admin
      JWT_SECRET: your_jwt_secret_here_make_it_very_long_and_secure
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./Backend/uploads:/app/uploads
    networks:
      - neoshala-network

  # Frontend React App
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: neoshala-frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - neoshala-network

volumes:
  mongodb_data:

networks:
  neoshala-network:
    driver: bridge
