name: Security Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Backend Dependencies
      run: |
        cd Backend
        npm ci
        
    - name: Install Frontend Dependencies
      run: |
        cd Frontend
        npm ci
        
    - name: Run Backend Security Audit (non-blocking)
      run: |
        cd Backend
        npm audit --audit-level=critical || true
        
    - name: Run Frontend Security Audit (non-blocking)
      run: |
        cd Frontend
        npm audit --audit-level=critical || true
        
    - name: Run CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
